version: '3.7'
services:
  web:
    build: .
    # env_file: backend/.env
    # command: daphne -b 0.0.0.0 backend.asgi:application
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "80:8000"
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=ShopDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres