# Generated by Django 3.2.7 on 2021-09-05 12:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_auto_20210904_2041'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 16', regex='^.{16}$')], verbose_name='Card Number')),
                ('card_holder_name', models.CharField(max_length=35, verbose_name='Card Holder Name')),
                ('expiration_month', models.CharField(max_length=2, verbose_name='Expiration Month')),
                ('expiration_year', models.CharField(max_length=2, verbose_name='Expiration Year')),
                ('cvv_number', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 3', regex='^.{3}$')], verbose_name='CVV Number')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Item Amount')),
                ('total_price', models.IntegerField(verbose_name='Total Price')),
                ('credit_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.creditcard')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.item')),
            ],
        ),
    ]
