# Generated by Django 3.2.7 on 2021-09-05 13:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_creditcard_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='cvv_number',
            field=models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 3', regex='^\\d{3}$')], verbose_name='CVV Number'),
        ),
    ]
