# Generated by Django 3.2.7 on 2021-09-06 18:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0012_auto_20210906_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='expiration_month',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Expiration Month'),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='expiration_year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)], verbose_name='Expiration Year'),
        ),
    ]
