# Generated by Django 3.2.7 on 2021-09-04 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='decription',
            new_name='description',
        ),
        migrations.AddField(
            model_name='user',
            name='items',
            field=models.ManyToManyField(to='bot.Item'),
        ),
    ]
