# Generated by Django 3.2.7 on 2021-09-06 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_auto_20210906_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='rating',
        ),
        migrations.AddField(
            model_name='userrating',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bot.item'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userrating',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bot.user'),
            preserve_default=False,
        ),
    ]
